# Generated by Django 3.2.6 on 2021-08-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review_of_Ongsimee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50)),
                ('starpoint', models.CharField(default='', max_length=10, verbose_name='별점')),
                ('price', models.IntegerField(default='')),
                ('withwhom', models.CharField(default='', max_length=10)),
                ('opinion', models.TextField()),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
