# Generated by Django 3.2.6 on 2021-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_of_ongsimee_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_of_ongsimee',
            name='withwhom',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
